from osbot_utils.helpers.Safe_Id import Safe_Id

FILE_ID__ARTICLE__MARKDOWN                     = Safe_Id('article-markdown'                )
FILE_ID__ARTICLE__TEXT__ENTITIES               = Safe_Id('text-entities'                   )
FILE_ID__ARTICLE__TEXT__ENTITIES__TITLE        = Safe_Id('text-entities-title'             )
FILE_ID__ARTICLE__TEXT__ENTITIES__DESCRIPTION  = Safe_Id('text-entities-description'       )
FILE_ID__ARTICLES__ALL                         = Safe_Id('articles-all'                    )
FILE_ID__ARTICLES__CURRENT                     = Safe_Id('articles-current'                )
FILE_ID__ARTICLES__NEW                         = Safe_Id('articles-new'                    )
FILE_ID__DAY__TEXT_ENTITIES                    = Safe_Id('text-entities-day'               )
FILE_ID__FEED_ARTICLE                          = Safe_Id('feed-article'                    )
FILE_ID__FEED__TEXT_ENTITIES                   = Safe_Id('feed-text-entities'              )
FILE_ID__FEED__TEXT_ENTITIES__DESCRIPTIONS     = Safe_Id('feed-text-entities-descriptions' )
FILE_ID__FEED__TEXT_ENTITIES__TITLES           = Safe_Id('feed-text-entities-titles'       )
FILE_ID__FEED__TEXT_ENTITIES__TITLES__TREE     = Safe_Id('feed-text-entities-titles-tree'  )
FILE_ID__TIMELINE__MGRAPH                      = Safe_Id('feed-timeline'                   )
FILE_ID__TIMELINE__DIFF                        = Safe_Id('feed-timeline-diff'              )