name: 'Run QUnit Tests'
description: 'Action to run QUnit tests'
inputs:
  node-version:
    description: 'Node.js version'
    required: true

runs:
  using: 'composite'
  steps:

    - name: Set up Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name             : Install dependencies
      shell            : bash
      working-directory: ./cbr_custom_data_feeds_ui
      run              : |
        npm install

    - name             : Run QUnit tests
      shell            : bash
      working-directory: ./cbr_custom_data_feeds_ui
      run              : |
        npm test
