name : Create Persona Digest
on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:

  run-tests:
    name: "Create Persona Digest"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "create persona digest"
        uses: ./.github/actions/my-feeds__create-persona-digest
        env:
          AWS_ACCOUNT_ID       : ${{ secrets.AWS_ACCOUNT_ID__774305572074        }}
          AWS_ACCESS_KEY_ID    : ${{ secrets.AWS_ACCESS_KEY_ID__774305572074     }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY__774305572074 }}
          AWS_DEFAULT_REGION   : ${{ secrets.AWS_DEFAULT_REGION__774305572074    }}