[providers.hacker-news]
provider_id = '49a0b7d7-6b33-4dfa-a993-5ab4be295ef2'
name        = 'hacker-news'
title       = 'The Hacker News'
url_website = 'https://thehackernews.com'
url_feed    = 'https://feeds.feedburner.com/TheHackersNews'
date_added  = '2024-12-28'

[providers.cso-online]
provider_id = '66932952-5a30-4325-b42b-14ee62bb6360'
name        = 'cso-online'
title       = 'CSO Online'
url_website = 'https://www.csoonline.com/uk/'
url_feed    = 'https://www.csoonline.com/feed/'
date_added  = '2024-12-28'

[providers.ncsc-news]
provider_id = 'b43f1050-7a28-40d2-baad-7c398c408e0a'
name        = 'ncsc'
title       = 'NCSC News'
url_website = 'https://www.ncsc.gov.uk'
url_feed    = 'https://www.ncsc.gov.uk/api/1/services/v1/news-rss-feed.xml'
date_added  = '2024-12-29'